version: '3.2'

services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    volumes:
      - pg_store:/var/lib/postgresql/data

volumes:
  pg_store: